
# query_parts1 = [
#     "Headquarters",
#     "Established Date",
#     "About the company",
#     "Industry",
#     "Company Financials",
#     "Company History",
#     "Awards and Accolades",
#     "Top 3 Competitor",
#     "Number of Employees",
#     "Number of Geographies",
#     "Exit Interview Top Themes",
#     "Employee Feedback",
#     "Engagement Survey Results",
#     "1-on-1 interview",
#     "Think Tank",
#     "SurveY",
#     "Top 3 Themes",
#     "Company Strategy",
#     "Purpose Vision Mission",
#     "Culture & Values",
#     "Employee Value Proposition",
#     "Brand Guidelines",
#     "External Comms",
#     "Internal Comm",
#     "Company Website",
#     "Careers Website",
#     "Careers page subscribers",
#     "Job Alert Signups",
#     "LinkedIn Info",
#     "Instagram Info",
#     "TikTok Info",
#     "Facebook Info",
#     "Twitter Info",
#     "Internal comms channels",
#     "Number of media mention",
#     "Targeted Skills",
#     "Targeted Geos",
#     "Ideal Educational Background",
#     "Ideal Employment Background",
#     "Number of Jobs Posted",
#     "Job Ad Clicks",
#     "Number of Direct Hires",
#     "What Attracts Talents",
#     "Reasons for Attrition",
#     "Sample JD",
#     "Recruitment Strategy",
#     "Average Time-to-Fill",
#     "Number of Offers Made",
#     "Number of Direct Applications",
#     "Number of Offers Accepted",
#     "Number of Employees",
#     "Number of Referrals",
#     "Number of Hires",
#     "Number of Referrals-to-Hires",
#     "ESAT Recommendability Score",
#     "Number of Re-hires",
#     "Avg. Tenure of Employees",
#     "Number of New Hires (in last 90 days)",
#     "Number of Early Exits (within 90 days)",
#     "Number of Awards Entered",
#     "Number of Awards Won",
#     "Glassdoor Score",
#     "Employee Testimonial 1",
#     "Employee Testimonial 2",
#     "Employee Testimonial 3",
#     "Employee Testimonial 4",
#     "Top 3 Competitors (Business)",
#     "Top 3 Competitors (Talent)"
# ]